### ISSUE TITLE
[기능 제안]: 커밋 전 질문 alert 

### ISSUE THREAD

**Issue by ImJongHoon** [Advanced-BOJ/Advanced-BOJ-extension#9]
### 한 줄 요약

alert 함수를 써서 간단하게 '커밋하시겠습니까?' 등의 질문을 출력

### 제안 기능 리스트

- [ ] 커밋 전 질문 alert

### 상세 설명

alert 함수를 써서 간단하게 '커밋하시겠습니까?' 등의 질문을 출력해주면 유저가 커밋 할지 안 할지 결정할 수 있고,
또 커밋이 되었는지 안 되었는지도 확인할 수 있어서 좋을 것 같다. 현재는 커밋이 진행되면 개발자 도구에서 확인해야해서 아쉽다.

**Comment by alirz-pixel** [comment]
@ImJongHoon 님
기능 제안 감사합니다.

alert 은 자주 뜰 경우, 사용자에게 불편함을 줄 수 있어서
해당 기능 제작과 함께 Advanced BOJ Extension 설정 페이지에 on/off 할 수 있는 옵션도 추가하겠습니다.

----
이와 별개로 커밋이 완료되었음을 알려주는 기능은 alert 말고
다른 방법으로 알려줄 수 있는지에 대해 고민해보겠습니다.

감사합니다.
